### ISSUE TITLE
Need help in modified onDrop function

### ISSUE THREAD

**Issue by aakashbajaj** [raymond-ong/noobformsv2#2]
https://github.com/raymond-ong/noobformsv2/blob/fce01768f95cfe3b35a85d6e83805081b96d3926/src/components/designerForm.js#L184

Hi @raymond-ong , can you please provide the changes made in onDrop library function?

**Comment by raymond-ong** [comment]
Hi, this is a react-grid-layout issue.
I posted a question/temp workaround here:
https://github.com/STRML/react-grid-layout/issues/1068
